### ISSUE TITLE
Worldpay

### ISSUE THREAD

**Issue by Horizon88** [continuous-software/42-cent#1]
Integration Request
===
**Name:** Worldpay
**Website:** http://www.worldpay.com/
**Developers Resources:** http://www.worldpay.com/us/developers/developer-resources

**Comment by kytwb** [comment]
Added in b3ddfc2702ebb98a7b9682328a4603b33524f2f7.

**Comment by Ajeya2691** [comment]
Hey, I'm a complete beginner to Open Source and discovered 42-cent
Right now, 7 other integration requests are open and I thought of looking at closed ones to see what changes/addition has to been done at each step(Since being a newbie I know nothing about this).
how can I see what was done ? @Horizon88
